package org.example.orderservice.saga;

public enum States {
    ORDER_CREATE, // Создание заказа
    ORDER_COMPLETE, // Заказ создан
    ORDER_FAILED, // Заказ завершился неудачей

    STOCK_UPDATE, // Склад обновился
    STOCK_ROLLBACK, // Откат обновления

    PAYMENT_CREATE, // Создание оплаты
    PAYMENT_CANCEL, // Отмена оплаты

    DELIVERY_CREATE, // Создание доставки
}

/*


1. ORDER_CREATE -> (STOCK_UPDATE)STOCK_UPDATE(STOCK_SUCCESS) -> (PAYMENT_CREATE)PAYMENT_CREATE(PAYMENT_SUCCESS) -> (DELIVERY_CREATE)DELIVERY_CREATE(DELIVERY_SUCCESS) -> (ORDER_COMPLETE)ORDER_COMPLETE
2. ORDER_CREATE -> (STOCK_UPDATE)STOCK_UPDATE(STOCK_SUCCESS) -> (PAYMENT_CREATE)PAYMENT_CREATE(PAYMENT_SUCCESS) -> (DELIVERY_CREATE)DELIVERY_CREATE(DELIVERY_FAILED)
    -> (PAYMENT_CANCEL)PAYMENT_CANCEL(PAYMENT_CANCEL_SUCCESS) -> (STOCK_ROLLBACK)STOCK_ROLLBACK(STOCK_ROLLBACK_SUCCESS) -> (ORDER_FAILED)ORDER_FAILED
3. ORDER_CREATE -> (STOCK_UPDATE)STOCK_UPDATE(STOCK_SUCCESS) -> (PAYMENT_CREATE)PAYMENT_CREATE(PAYMENT_FAILED) -> (STOCK_ROLLBACK)STOCK_ROLLBACK(STOCK_ROLLBACK_SUCCESS) -> (ORDER_FAILED)ORDER_FAILED
4. ORDER_CREATE -> (STOCK_UPDATE)STOCK_UPDATE(STOCK_FAILED) -> (ORDER_FAILED)ORDER_FAILED
5. ORDER_CREATE -> (ORDER_FAILED)ORDER_FAILED




 */


