server:
  port: 8000
  servlet:
    context-path: /order-service

logging:
  level:
    org:
      springframework:
        cloud: debug

spring:
  application:
    name: order-service

  main:
    banner-mode: off

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.globally_quoted_identifiers: true

  config:
    import: "optional:kubernetes:"
  cloud:
    kubernetes:
      reload:
        enabled: true
        strategy: refresh
      config:
        fail-fast: true
      secrets:
        fail-fast: true
    function:
      routing-expression: headers['type']
      definition: functionRouter
    stream:
      bindings:
        functionRouter-in-0:
          destination: orderSagaReplies
          group: orders
        orderSagaReplies-out-0:
          destination: orderSagaReplies

        stockProducer-out-0:
          destination: stockTopic
          group: stock

        paymentProducer-out-0:
          destination: paymentTopic
          group: payment

        deliveryProducer-out-0:
          destination: deliveryTopic
          group: delivery

      kafka:
        binder:
          headers:
            - type

app:
  delivery-service: http://delivery-service